/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/bar': RouteRecordInfo<'/bar', '/bar', Record<never, never>, Record<never, never>>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/chat': RouteRecordInfo<'/chat', '/chat', Record<never, never>, Record<never, never>>,
    '/chat-zh': RouteRecordInfo<'/chat-zh', '/chat-zh', Record<never, never>, Record<never, never>>,
    '/collective-sponsor-onetime': RouteRecordInfo<'/collective-sponsor-onetime', '/collective-sponsor-onetime', Record<never, never>, Record<never, never>>,
    '/demos': RouteRecordInfo<'/demos', '/demos', Record<never, never>, Record<never, never>>,
    '/giving-talks': RouteRecordInfo<'/giving-talks', '/giving-talks', Record<never, never>, Record<never, never>>,
    '/media': RouteRecordInfo<'/media', '/media', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/photos': RouteRecordInfo<'/photos', '/photos', Record<never, never>, Record<never, never>>,
    '/podcasts': RouteRecordInfo<'/podcasts', '/podcasts', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/nuxt-cpuprofile': RouteRecordInfo<'/posts/nuxt-cpuprofile', '/posts/nuxt-cpuprofile', Record<never, never>, Record<never, never>>,
    '/posts/PIBIC-Camadas-Médias-e-o-seu-Espaço-Escolar': RouteRecordInfo<'/posts/PIBIC-Camadas-Médias-e-o-seu-Espaço-Escolar', '/posts/PIBIC-Camadas-Médias-e-o-seu-Espaço-Escolar', Record<never, never>, Record<never, never>>,
    '/posts/primeiro post': RouteRecordInfo<'/posts/primeiro post', '/posts/primeiro post', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/sponsors-list': RouteRecordInfo<'/sponsors-list', '/sponsors-list', Record<never, never>, Record<never, never>>,
    '/streams': RouteRecordInfo<'/streams', '/streams', Record<never, never>, Record<never, never>>,
    '/talks': RouteRecordInfo<'/talks', '/talks', Record<never, never>, Record<never, never>>,
    '/trash/about-yak-shaving': RouteRecordInfo<'/trash/about-yak-shaving', '/trash/about-yak-shaving', Record<never, never>, Record<never, never>>,
    '/trash/about-yak-shaving-zh': RouteRecordInfo<'/trash/about-yak-shaving-zh', '/trash/about-yak-shaving-zh', Record<never, never>, Record<never, never>>,
    '/trash/ai-qrcode': RouteRecordInfo<'/trash/ai-qrcode', '/trash/ai-qrcode', Record<never, never>, Record<never, never>>,
    '/trash/ai-qrcode-101': RouteRecordInfo<'/trash/ai-qrcode-101', '/trash/ai-qrcode-101', Record<never, never>, Record<never, never>>,
    '/trash/ai-qrcode-refine': RouteRecordInfo<'/trash/ai-qrcode-refine', '/trash/ai-qrcode-refine', Record<never, never>, Record<never, never>>,
    '/trash/animated-svg-logo': RouteRecordInfo<'/trash/animated-svg-logo', '/trash/animated-svg-logo', Record<never, never>, Record<never, never>>,
    '/trash/async-sync-in-between': RouteRecordInfo<'/trash/async-sync-in-between', '/trash/async-sync-in-between', Record<never, never>, Record<never, never>>,
    '/trash/async-with-composition-api': RouteRecordInfo<'/trash/async-with-composition-api', '/trash/async-with-composition-api', Record<never, never>, Record<never, never>>,
    '/trash/binfe-2020-zh': RouteRecordInfo<'/trash/binfe-2020-zh', '/trash/binfe-2020-zh', Record<never, never>, Record<never, never>>,
    '/trash/bonjour-paris': RouteRecordInfo<'/trash/bonjour-paris', '/trash/bonjour-paris', Record<never, never>, Record<never, never>>,
    '/trash/break-lines-in-js': RouteRecordInfo<'/trash/break-lines-in-js', '/trash/break-lines-in-js', Record<never, never>, Record<never, never>>,
    '/trash/categorize-deps': RouteRecordInfo<'/trash/categorize-deps', '/trash/categorize-deps', Record<never, never>, Record<never, never>>,
    '/trash/color-scheme-for-vscode-ext': RouteRecordInfo<'/trash/color-scheme-for-vscode-ext', '/trash/color-scheme-for-vscode-ext', Record<never, never>, Record<never, never>>,
    '/trash/composable-vue-vueconf-china-2021': RouteRecordInfo<'/trash/composable-vue-vueconf-china-2021', '/trash/composable-vue-vueconf-china-2021', Record<never, never>, Record<never, never>>,
    '/trash/composable-vue-vueday-2021': RouteRecordInfo<'/trash/composable-vue-vueday-2021', '/trash/composable-vue-vueday-2021', Record<never, never>, Record<never, never>>,
    '/trash/destructuring-with-object-or-array': RouteRecordInfo<'/trash/destructuring-with-object-or-array', '/trash/destructuring-with-object-or-array', Record<never, never>, Record<never, never>>,
    '/trash/dev-ssr-on-nuxt': RouteRecordInfo<'/trash/dev-ssr-on-nuxt', '/trash/dev-ssr-on-nuxt', Record<never, never>, Record<never, never>>,
    '/trash/domain-email': RouteRecordInfo<'/trash/domain-email', '/trash/domain-email', Record<never, never>, Record<never, never>>,
    '/trash/epoch-semver': RouteRecordInfo<'/trash/epoch-semver', '/trash/epoch-semver', Record<never, never>, Record<never, never>>,
    '/trash/eslint-config-inspector': RouteRecordInfo<'/trash/eslint-config-inspector', '/trash/eslint-config-inspector', Record<never, never>, Record<never, never>>,
    '/trash/evolution-of-shiki-v1': RouteRecordInfo<'/trash/evolution-of-shiki-v1', '/trash/evolution-of-shiki-v1', Record<never, never>, Record<never, never>>,
    '/trash/get-package-root': RouteRecordInfo<'/trash/get-package-root', '/trash/get-package-root', Record<never, never>, Record<never, never>>,
    '/trash/github-alerts': RouteRecordInfo<'/trash/github-alerts', '/trash/github-alerts', Record<never, never>, Record<never, never>>,
    '/trash/github-co-authors': RouteRecordInfo<'/trash/github-co-authors', '/trash/github-co-authors', Record<never, never>, Record<never, never>>,
    '/trash/hello-tokyo': RouteRecordInfo<'/trash/hello-tokyo', '/trash/hello-tokyo', Record<never, never>, Record<never, never>>,
    '/trash/icons-in-pure-css': RouteRecordInfo<'/trash/icons-in-pure-css', '/trash/icons-in-pure-css', Record<never, never>, Record<never, never>>,
    '/trash/icons-in-pure-css-zh': RouteRecordInfo<'/trash/icons-in-pure-css-zh', '/trash/icons-in-pure-css-zh', Record<never, never>, Record<never, never>>,
    '/trash/introducing-nuxt-devtools': RouteRecordInfo<'/trash/introducing-nuxt-devtools', '/trash/introducing-nuxt-devtools', Record<never, never>, Record<never, never>>,
    '/trash/introduction-to-vitest-vue-nation-2022': RouteRecordInfo<'/trash/introduction-to-vitest-vue-nation-2022', '/trash/introduction-to-vitest-vue-nation-2022', Record<never, never>, Record<never, never>>,
    '/trash/isomorphic-dirname': RouteRecordInfo<'/trash/isomorphic-dirname', '/trash/isomorphic-dirname', Record<never, never>, Record<never, never>>,
    '/trash/journey-with-icons': RouteRecordInfo<'/trash/journey-with-icons', '/trash/journey-with-icons', Record<never, never>, Record<never, never>>,
    '/trash/journey-with-icons-continues': RouteRecordInfo<'/trash/journey-with-icons-continues', '/trash/journey-with-icons-continues', Record<never, never>, Record<never, never>>,
    '/trash/make-libraries-working-with-vue-2-and-3': RouteRecordInfo<'/trash/make-libraries-working-with-vue-2-and-3', '/trash/make-libraries-working-with-vue-2-and-3', Record<never, never>, Record<never, never>>,
    '/trash/manage-github-notifications-2023': RouteRecordInfo<'/trash/manage-github-notifications-2023', '/trash/manage-github-notifications-2023', Record<never, never>, Record<never, never>>,
    '/trash/match-chinese-characters': RouteRecordInfo<'/trash/match-chinese-characters', '/trash/match-chinese-characters', Record<never, never>, Record<never, never>>,
    '/trash/match-quotes-in-pairs': RouteRecordInfo<'/trash/match-quotes-in-pairs', '/trash/match-quotes-in-pairs', Record<never, never>, Record<never, never>>,
    '/trash/mental-health-oss': RouteRecordInfo<'/trash/mental-health-oss', '/trash/mental-health-oss', Record<never, never>, Record<never, never>>,
    '/trash/mental-health-oss-zh': RouteRecordInfo<'/trash/mental-health-oss-zh', '/trash/mental-health-oss-zh', Record<never, never>, Record<never, never>>,
    '/trash/move-on-to-esm-only': RouteRecordInfo<'/trash/move-on-to-esm-only', '/trash/move-on-to-esm-only', Record<never, never>, Record<never, never>>,
    '/trash/netlify-redirects': RouteRecordInfo<'/trash/netlify-redirects', '/trash/netlify-redirects', Record<never, never>, Record<never, never>>,
    '/trash/new-house': RouteRecordInfo<'/trash/new-house', '/trash/new-house', Record<never, never>, Record<never, never>>,
    '/trash/new-ways-to-vue-london-2021': RouteRecordInfo<'/trash/new-ways-to-vue-london-2021', '/trash/new-ways-to-vue-london-2021', Record<never, never>, Record<never, never>>,
    '/trash/new-ways-to-vue-taiwan-2021': RouteRecordInfo<'/trash/new-ways-to-vue-taiwan-2021', '/trash/new-ways-to-vue-taiwan-2021', Record<never, never>, Record<never, never>>,
    '/trash/now-and-future-devtools-nuxt-nation-2023': RouteRecordInfo<'/trash/now-and-future-devtools-nuxt-nation-2023', '/trash/now-and-future-devtools-nuxt-nation-2023', Record<never, never>, Record<never, never>>,
    '/trash/npm-binary-mirrors': RouteRecordInfo<'/trash/npm-binary-mirrors', '/trash/npm-binary-mirrors', Record<never, never>, Record<never, never>>,
    '/trash/nuxt-devtools-v1': RouteRecordInfo<'/trash/nuxt-devtools-v1', '/trash/nuxt-devtools-v1', Record<never, never>, Record<never, never>>,
    '/trash/nuxt-dx-2023': RouteRecordInfo<'/trash/nuxt-dx-2023', '/trash/nuxt-dx-2023', Record<never, never>, Record<never, never>>,
    '/trash/nuxt-dx-strasbourg-2023': RouteRecordInfo<'/trash/nuxt-dx-strasbourg-2023', '/trash/nuxt-dx-strasbourg-2023', Record<never, never>, Record<never, never>>,
    '/trash/nuxt-icon-v1': RouteRecordInfo<'/trash/nuxt-icon-v1', '/trash/nuxt-icon-v1', Record<never, never>, Record<never, never>>,
    '/trash/ohayo-tokyo': RouteRecordInfo<'/trash/ohayo-tokyo', '/trash/ohayo-tokyo', Record<never, never>, Record<never, never>>,
    '/trash/optimize-await': RouteRecordInfo<'/trash/optimize-await', '/trash/optimize-await', Record<never, never>, Record<never, never>>,
    '/trash/patterns-of-vueuse-vuefes-japan-2022': RouteRecordInfo<'/trash/patterns-of-vueuse-vuefes-japan-2022', '/trash/patterns-of-vueuse-vuefes-japan-2022', Record<never, never>, Record<never, never>>,
    '/trash/photos-page': RouteRecordInfo<'/trash/photos-page', '/trash/photos-page', Record<never, never>, Record<never, never>>,
    '/trash/pnpm-external-disk': RouteRecordInfo<'/trash/pnpm-external-disk', '/trash/pnpm-external-disk', Record<never, never>, Record<never, never>>,
    '/trash/publish-esm-and-cjs': RouteRecordInfo<'/trash/publish-esm-and-cjs', '/trash/publish-esm-and-cjs', Record<never, never>, Record<never, never>>,
    '/trash/range-in-javascript': RouteRecordInfo<'/trash/range-in-javascript', '/trash/range-in-javascript', Record<never, never>, Record<never, never>>,
    '/trash/reflection-of-speaking-in-public': RouteRecordInfo<'/trash/reflection-of-speaking-in-public', '/trash/reflection-of-speaking-in-public', Record<never, never>, Record<never, never>>,
    '/trash/refreshed-nuxt-eslint': RouteRecordInfo<'/trash/refreshed-nuxt-eslint', '/trash/refreshed-nuxt-eslint', Record<never, never>, Record<never, never>>,
    '/trash/reimagine-atomic-css': RouteRecordInfo<'/trash/reimagine-atomic-css', '/trash/reimagine-atomic-css', Record<never, never>, Record<never, never>>,
    '/trash/reimagine-atomic-css-zh': RouteRecordInfo<'/trash/reimagine-atomic-css-zh', '/trash/reimagine-atomic-css-zh', Record<never, never>, Record<never, never>>,
    '/trash/rewrite-in-vite': RouteRecordInfo<'/trash/rewrite-in-vite', '/trash/rewrite-in-vite', Record<never, never>, Record<never, never>>,
    '/trash/roads-to-oss-progressive-vueams-2024': RouteRecordInfo<'/trash/roads-to-oss-progressive-vueams-2024', '/trash/roads-to-oss-progressive-vueams-2024', Record<never, never>, Record<never, never>>,
    '/trash/roads-to-oss-set-theory-react-paris-2024': RouteRecordInfo<'/trash/roads-to-oss-set-theory-react-paris-2024', '/trash/roads-to-oss-set-theory-react-paris-2024', Record<never, never>, Record<never, never>>,
    '/trash/roads-to-oss-set-theory-viteconf-2023': RouteRecordInfo<'/trash/roads-to-oss-set-theory-viteconf-2023', '/trash/roads-to-oss-set-theory-viteconf-2023', Record<never, never>, Record<never, never>>,
    '/trash/roads-to-oss-set-theory-vuefesjapan-2023': RouteRecordInfo<'/trash/roads-to-oss-set-theory-vuefesjapan-2023', '/trash/roads-to-oss-set-theory-vuefesjapan-2023', Record<never, never>, Record<never, never>>,
    '/trash/shiki-magic-move': RouteRecordInfo<'/trash/shiki-magic-move', '/trash/shiki-magic-move', Record<never, never>, Record<never, never>>,
    '/trash/shikiji-twoslash': RouteRecordInfo<'/trash/shikiji-twoslash', '/trash/shikiji-twoslash', Record<never, never>, Record<never, never>>,
    '/trash/sliding-enter-animation': RouteRecordInfo<'/trash/sliding-enter-animation', '/trash/sliding-enter-animation', Record<never, never>, Record<never, never>>,
    '/trash/sponsorship-forwarding': RouteRecordInfo<'/trash/sponsorship-forwarding', '/trash/sponsorship-forwarding', Record<never, never>, Record<never, never>>,
    '/trash/type-inferencing-in-vue': RouteRecordInfo<'/trash/type-inferencing-in-vue', '/trash/type-inferencing-in-vue', Record<never, never>, Record<never, never>>,
    '/trash/type-your-config': RouteRecordInfo<'/trash/type-your-config', '/trash/type-your-config', Record<never, never>, Record<never, never>>,
    '/trash/typed-provide-and-inject-in-vue': RouteRecordInfo<'/trash/typed-provide-and-inject-in-vue', '/trash/typed-provide-and-inject-in-vue', Record<never, never>, Record<never, never>>,
    '/trash/types-for-sub-modules': RouteRecordInfo<'/trash/types-for-sub-modules', '/trash/types-for-sub-modules', Record<never, never>, Record<never, never>>,
    '/trash/vite-on-demand-dx-viteconf-2022': RouteRecordInfo<'/trash/vite-on-demand-dx-viteconf-2022', '/trash/vite-on-demand-dx-viteconf-2022', Record<never, never>, Record<never, never>>,
    '/trash/vue-beijing-2021': RouteRecordInfo<'/trash/vue-beijing-2021', '/trash/vue-beijing-2021', Record<never, never>, Record<never, never>>,
    '/trash/vueuse-best-practice-vueconf-china-2022': RouteRecordInfo<'/trash/vueuse-best-practice-vueconf-china-2022', '/trash/vueuse-best-practice-vueconf-china-2022', Record<never, never>, Record<never, never>>,
    '/trash/watch-with-reactivity': RouteRecordInfo<'/trash/watch-with-reactivity', '/trash/watch-with-reactivity', Record<never, never>, Record<never, never>>,
    '/trash/why-not-prettier': RouteRecordInfo<'/trash/why-not-prettier', '/trash/why-not-prettier', Record<never, never>, Record<never, never>>,
    '/trash/why-not-prettier-zh': RouteRecordInfo<'/trash/why-not-prettier-zh', '/trash/why-not-prettier-zh', Record<never, never>, Record<never, never>>,
    '/trash/why-reproductions-are-required': RouteRecordInfo<'/trash/why-reproductions-are-required', '/trash/why-reproductions-are-required', Record<never, never>, Record<never, never>>,
    '/trash/why-reproductions-are-required-zh': RouteRecordInfo<'/trash/why-reproductions-are-required-zh', '/trash/why-reproductions-are-required-zh', Record<never, never>, Record<never, never>>,
    '/trash/windicss-and-tailwind-jit': RouteRecordInfo<'/trash/windicss-and-tailwind-jit', '/trash/windicss-and-tailwind-jit', Record<never, never>, Record<never, never>>,
    '/use': RouteRecordInfo<'/use', '/use', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes: '/'
      views: never
    }
    'pages/[...404].md': {
      routes: '/[...404]'
      views: never
    }
    'pages/bar.md': {
      routes: '/bar'
      views: never
    }
    'pages/bookmarks.md': {
      routes: '/bookmarks'
      views: never
    }
    'pages/chat.md': {
      routes: '/chat'
      views: never
    }
    'pages/chat-zh.md': {
      routes: '/chat-zh'
      views: never
    }
    'pages/collective-sponsor-onetime.md': {
      routes: '/collective-sponsor-onetime'
      views: never
    }
    'pages/demos.md': {
      routes: '/demos'
      views: never
    }
    'pages/giving-talks.md': {
      routes: '/giving-talks'
      views: never
    }
    'pages/media.md': {
      routes: '/media'
      views: never
    }
    'pages/notes.md': {
      routes: '/notes'
      views: never
    }
    'pages/photos.md': {
      routes: '/photos'
      views: never
    }
    'pages/podcasts.md': {
      routes: '/podcasts'
      views: never
    }
    'pages/posts/index.md': {
      routes: '/posts/'
      views: never
    }
    'pages/posts/nuxt-cpuprofile.md': {
      routes: '/posts/nuxt-cpuprofile'
      views: never
    }
    'pages/posts/PIBIC-Camadas-Médias-e-o-seu-Espaço-Escolar.md': {
      routes: '/posts/PIBIC-Camadas-Médias-e-o-seu-Espaço-Escolar'
      views: never
    }
    'pages/posts/primeiro post.md': {
      routes: '/posts/primeiro post'
      views: never
    }
    'pages/projects.md': {
      routes: '/projects'
      views: never
    }
    'pages/sponsors-list.md': {
      routes: '/sponsors-list'
      views: never
    }
    'pages/streams.md': {
      routes: '/streams'
      views: never
    }
    'pages/talks.md': {
      routes: '/talks'
      views: never
    }
    'pages/trash/about-yak-shaving.md': {
      routes: '/trash/about-yak-shaving'
      views: never
    }
    'pages/trash/about-yak-shaving-zh.md': {
      routes: '/trash/about-yak-shaving-zh'
      views: never
    }
    'pages/trash/ai-qrcode.md': {
      routes: '/trash/ai-qrcode'
      views: never
    }
    'pages/trash/ai-qrcode-101.md': {
      routes: '/trash/ai-qrcode-101'
      views: never
    }
    'pages/trash/ai-qrcode-refine.md': {
      routes: '/trash/ai-qrcode-refine'
      views: never
    }
    'pages/trash/animated-svg-logo.md': {
      routes: '/trash/animated-svg-logo'
      views: never
    }
    'pages/trash/async-sync-in-between.md': {
      routes: '/trash/async-sync-in-between'
      views: never
    }
    'pages/trash/async-with-composition-api.md': {
      routes: '/trash/async-with-composition-api'
      views: never
    }
    'pages/trash/binfe-2020-zh.md': {
      routes: '/trash/binfe-2020-zh'
      views: never
    }
    'pages/trash/bonjour-paris.md': {
      routes: '/trash/bonjour-paris'
      views: never
    }
    'pages/trash/break-lines-in-js.md': {
      routes: '/trash/break-lines-in-js'
      views: never
    }
    'pages/trash/categorize-deps.md': {
      routes: '/trash/categorize-deps'
      views: never
    }
    'pages/trash/color-scheme-for-vscode-ext.md': {
      routes: '/trash/color-scheme-for-vscode-ext'
      views: never
    }
    'pages/trash/composable-vue-vueconf-china-2021.md': {
      routes: '/trash/composable-vue-vueconf-china-2021'
      views: never
    }
    'pages/trash/composable-vue-vueday-2021.md': {
      routes: '/trash/composable-vue-vueday-2021'
      views: never
    }
    'pages/trash/destructuring-with-object-or-array.md': {
      routes: '/trash/destructuring-with-object-or-array'
      views: never
    }
    'pages/trash/dev-ssr-on-nuxt.md': {
      routes: '/trash/dev-ssr-on-nuxt'
      views: never
    }
    'pages/trash/domain-email.md': {
      routes: '/trash/domain-email'
      views: never
    }
    'pages/trash/epoch-semver.md': {
      routes: '/trash/epoch-semver'
      views: never
    }
    'pages/trash/eslint-config-inspector.md': {
      routes: '/trash/eslint-config-inspector'
      views: never
    }
    'pages/trash/evolution-of-shiki-v1.md': {
      routes: '/trash/evolution-of-shiki-v1'
      views: never
    }
    'pages/trash/get-package-root.md': {
      routes: '/trash/get-package-root'
      views: never
    }
    'pages/trash/github-alerts.md': {
      routes: '/trash/github-alerts'
      views: never
    }
    'pages/trash/github-co-authors.md': {
      routes: '/trash/github-co-authors'
      views: never
    }
    'pages/trash/hello-tokyo.md': {
      routes: '/trash/hello-tokyo'
      views: never
    }
    'pages/trash/icons-in-pure-css.md': {
      routes: '/trash/icons-in-pure-css'
      views: never
    }
    'pages/trash/icons-in-pure-css-zh.md': {
      routes: '/trash/icons-in-pure-css-zh'
      views: never
    }
    'pages/trash/introducing-nuxt-devtools.md': {
      routes: '/trash/introducing-nuxt-devtools'
      views: never
    }
    'pages/trash/introduction-to-vitest-vue-nation-2022.md': {
      routes: '/trash/introduction-to-vitest-vue-nation-2022'
      views: never
    }
    'pages/trash/isomorphic-dirname.md': {
      routes: '/trash/isomorphic-dirname'
      views: never
    }
    'pages/trash/journey-with-icons.md': {
      routes: '/trash/journey-with-icons'
      views: never
    }
    'pages/trash/journey-with-icons-continues.md': {
      routes: '/trash/journey-with-icons-continues'
      views: never
    }
    'pages/trash/make-libraries-working-with-vue-2-and-3.md': {
      routes: '/trash/make-libraries-working-with-vue-2-and-3'
      views: never
    }
    'pages/trash/manage-github-notifications-2023.md': {
      routes: '/trash/manage-github-notifications-2023'
      views: never
    }
    'pages/trash/match-chinese-characters.md': {
      routes: '/trash/match-chinese-characters'
      views: never
    }
    'pages/trash/match-quotes-in-pairs.md': {
      routes: '/trash/match-quotes-in-pairs'
      views: never
    }
    'pages/trash/mental-health-oss.md': {
      routes: '/trash/mental-health-oss'
      views: never
    }
    'pages/trash/mental-health-oss-zh.md': {
      routes: '/trash/mental-health-oss-zh'
      views: never
    }
    'pages/trash/move-on-to-esm-only.md': {
      routes: '/trash/move-on-to-esm-only'
      views: never
    }
    'pages/trash/netlify-redirects.md': {
      routes: '/trash/netlify-redirects'
      views: never
    }
    'pages/trash/new-house.md': {
      routes: '/trash/new-house'
      views: never
    }
    'pages/trash/new-ways-to-vue-london-2021.md': {
      routes: '/trash/new-ways-to-vue-london-2021'
      views: never
    }
    'pages/trash/new-ways-to-vue-taiwan-2021.md': {
      routes: '/trash/new-ways-to-vue-taiwan-2021'
      views: never
    }
    'pages/trash/now-and-future-devtools-nuxt-nation-2023.md': {
      routes: '/trash/now-and-future-devtools-nuxt-nation-2023'
      views: never
    }
    'pages/trash/npm-binary-mirrors.md': {
      routes: '/trash/npm-binary-mirrors'
      views: never
    }
    'pages/trash/nuxt-devtools-v1.md': {
      routes: '/trash/nuxt-devtools-v1'
      views: never
    }
    'pages/trash/nuxt-dx-2023.md': {
      routes: '/trash/nuxt-dx-2023'
      views: never
    }
    'pages/trash/nuxt-dx-strasbourg-2023.md': {
      routes: '/trash/nuxt-dx-strasbourg-2023'
      views: never
    }
    'pages/trash/nuxt-icon-v1.md': {
      routes: '/trash/nuxt-icon-v1'
      views: never
    }
    'pages/trash/ohayo-tokyo.md': {
      routes: '/trash/ohayo-tokyo'
      views: never
    }
    'pages/trash/optimize-await.md': {
      routes: '/trash/optimize-await'
      views: never
    }
    'pages/trash/patterns-of-vueuse-vuefes-japan-2022.md': {
      routes: '/trash/patterns-of-vueuse-vuefes-japan-2022'
      views: never
    }
    'pages/trash/photos-page.md': {
      routes: '/trash/photos-page'
      views: never
    }
    'pages/trash/pnpm-external-disk.md': {
      routes: '/trash/pnpm-external-disk'
      views: never
    }
    'pages/trash/publish-esm-and-cjs.md': {
      routes: '/trash/publish-esm-and-cjs'
      views: never
    }
    'pages/trash/range-in-javascript.md': {
      routes: '/trash/range-in-javascript'
      views: never
    }
    'pages/trash/reflection-of-speaking-in-public.md': {
      routes: '/trash/reflection-of-speaking-in-public'
      views: never
    }
    'pages/trash/refreshed-nuxt-eslint.md': {
      routes: '/trash/refreshed-nuxt-eslint'
      views: never
    }
    'pages/trash/reimagine-atomic-css.md': {
      routes: '/trash/reimagine-atomic-css'
      views: never
    }
    'pages/trash/reimagine-atomic-css-zh.md': {
      routes: '/trash/reimagine-atomic-css-zh'
      views: never
    }
    'pages/trash/rewrite-in-vite.md': {
      routes: '/trash/rewrite-in-vite'
      views: never
    }
    'pages/trash/roads-to-oss-progressive-vueams-2024.md': {
      routes: '/trash/roads-to-oss-progressive-vueams-2024'
      views: never
    }
    'pages/trash/roads-to-oss-set-theory-react-paris-2024.md': {
      routes: '/trash/roads-to-oss-set-theory-react-paris-2024'
      views: never
    }
    'pages/trash/roads-to-oss-set-theory-viteconf-2023.md': {
      routes: '/trash/roads-to-oss-set-theory-viteconf-2023'
      views: never
    }
    'pages/trash/roads-to-oss-set-theory-vuefesjapan-2023.md': {
      routes: '/trash/roads-to-oss-set-theory-vuefesjapan-2023'
      views: never
    }
    'pages/trash/shiki-magic-move.md': {
      routes: '/trash/shiki-magic-move'
      views: never
    }
    'pages/trash/shikiji-twoslash.md': {
      routes: '/trash/shikiji-twoslash'
      views: never
    }
    'pages/trash/sliding-enter-animation.md': {
      routes: '/trash/sliding-enter-animation'
      views: never
    }
    'pages/trash/sponsorship-forwarding.md': {
      routes: '/trash/sponsorship-forwarding'
      views: never
    }
    'pages/trash/type-inferencing-in-vue.md': {
      routes: '/trash/type-inferencing-in-vue'
      views: never
    }
    'pages/trash/type-your-config.md': {
      routes: '/trash/type-your-config'
      views: never
    }
    'pages/trash/typed-provide-and-inject-in-vue.md': {
      routes: '/trash/typed-provide-and-inject-in-vue'
      views: never
    }
    'pages/trash/types-for-sub-modules.md': {
      routes: '/trash/types-for-sub-modules'
      views: never
    }
    'pages/trash/vite-on-demand-dx-viteconf-2022.md': {
      routes: '/trash/vite-on-demand-dx-viteconf-2022'
      views: never
    }
    'pages/trash/vue-beijing-2021.md': {
      routes: '/trash/vue-beijing-2021'
      views: never
    }
    'pages/trash/vueuse-best-practice-vueconf-china-2022.md': {
      routes: '/trash/vueuse-best-practice-vueconf-china-2022'
      views: never
    }
    'pages/trash/watch-with-reactivity.md': {
      routes: '/trash/watch-with-reactivity'
      views: never
    }
    'pages/trash/why-not-prettier.md': {
      routes: '/trash/why-not-prettier'
      views: never
    }
    'pages/trash/why-not-prettier-zh.md': {
      routes: '/trash/why-not-prettier-zh'
      views: never
    }
    'pages/trash/why-reproductions-are-required.md': {
      routes: '/trash/why-reproductions-are-required'
      views: never
    }
    'pages/trash/why-reproductions-are-required-zh.md': {
      routes: '/trash/why-reproductions-are-required-zh'
      views: never
    }
    'pages/trash/windicss-and-tailwind-jit.md': {
      routes: '/trash/windicss-and-tailwind-jit'
      views: never
    }
    'pages/use.md': {
      routes: '/use'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
